### ISSUE TITLE
Is it possible to connect to smtp servers through proxy servers?

### ISSUE THREAD

**Issue by chamnap** [bighappyworld/email-verify#15]
I need to check and verify many emails, and i think my ip address will be treated as spam. Therefore, I would like to connect through proxy servers. Is it possible to connect through proxy servers?

Could you give me a clue?

**Comment by bighappyworld** [comment]
It's possible. But maybe not unless you fork this, make some modifications, and write a custom proxy. This is a direct socket connection and there is nothing in the implemented protocol that would allow it.

**Comment by chamnap** [comment]
@bighappyworld, any clue to make it work through proxy servers?

**Comment by bighappyworld** [comment]
https://nodejs.org/api/net.html

This is what I'm doing for a socket connection. If you read, there are no headers. It is because protocols are implemented on top of this, like the HTTP protocol. A proxy will typically be something like an HTTP proxy. Not a pure socket proxy. A pure socket proxy is more like a port forwarding configuration on a router.

https://en.wikipedia.org/wiki/OSI_model

Networking is done in layers, each layer basically adds on different information that is used by that layer. The socket connection is effectively Layer 4, the transport layer. If you are implementing a software proxy, it would be at a higher layer and you'd be adding additional information to the data.

If you want this to work with generic out of the box proxies, you're out of luck... for example, if you try with a different application layer connecting to the SMTP server, it will send additional header information the moment you open the socket. This will likely cause the SMTP server to cut the connection.

**Comment by chamnap** [comment]
Thanks for your explanation. I'm pretty new to socket programming. Yeah, I have seen your code that it sends direct connection to smtp server. 

Do you know any npm modules that are able to do this? I would like to connect through some proxy paid services.

**Comment by bighappyworld** [comment]
No. I suggest learning about the network layers and about socket programming. You are going to have to write your own.
