### ISSUE TITLE
yahoo false negative

### ISSUE THREAD

**Issue by Peege151** [bighappyworld/email-verify#18]
I tried to verify my yahoo account.  It comes back as success: false.  It is my yahoo address so I know it's valid and gets email daily.

Thoughts?

**Comment by bighappyworld** [comment]
This module only does the SMTP protocol. You are still at the mercy of all of the other services out there and connecting to their email server. If you really want to know, you should telnet to the yahoo SMTP server and manually do the SMTP handshake.

I recently did this to another email server and turns out that the IP address that I connected to was part of an IP address block that some spam filter "blocks" because they are not server IPs but reserved for residential use by my ISP. Since I was connecting from one of those, it knew I wasn't a real mail server and so the spam filter rejected it.

There are a ton of different cases that can cause this, but that's an example I recently encountered.

**Comment by tofutim** [comment]
Wow that is pretty smart.

**Comment by tofutim** [comment]
kickbox claims to be able to do much of the smtp handshake work but it is pricy.

**Comment by bighappyworld** [comment]
If you did your verification FROM the same server as your email server and you have an MX record pointing to it along with all the proper DKIM, DMARC, reverse pointer record,  & other stuff working for you, you won't fail as many spam filters. But you'd also have to check for your server IP on blacklists etc. Email is a nasty beast because of all the spammers and so they make it really painful to really do proper validation. This is why a service that does it can possibly make money.
