### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by dayAlone** [bighappyworld/email-verify#20]
Hello, some servers (mail.ru for example) always return false and error "550 SMTP is available only with SSL or TLS connection enabled."

Can you add SSL support?

**Comment by bighappyworld** [comment]
No time for that at the moment. If you have a free moment, you could give a pull request?

**Comment by lucasjans** [comment]
I may ask one of my team members to contribute to this. Any research on how to do this would be helpful.

**Comment by hhsadiq** [comment]
@dayAlone @lucasjans @bighappyworld Hey guys, so this package supports SSL or TLS now? And if not, what is workaround currently. Did you use some other package to solve this issue?

**Comment by bighappyworld** [comment]
@hhsadiq there hasn't been any changes adding SSL / TLS support, I am not aware of any workarounds people have made. to me this hasn't been as much of a problem as email servers that say "OK" for all email addresses, and I'm not sure about how to solve this one.

if you'd like to add TLS / SSL support because you've been having lots of trouble with it, i'd be happy to accept a pull request

**Comment by hhsadiq** [comment]
@bighappyworld thanks for replying. Actually I am still struggling to find the root cause of issue. I am having issue when verifying gmail powered custom emails or yahoo emails. My tool is marking all emails as valid from these two sources. And interestingly when using online email verification tools like http://email-checker.net/ or http://verify-email.org/ or http://www.verifyemailaddress.org/, they are also showing such emails as valid.

E.g alkjsfdlkasjlkdfjasdljflkasjflkjlksfjafdlajsfjl@yahoo.com or alkjsfdlkasjlkdfjasdljflkasjflkjlksfjafdlajsfjl@punch.cool (our company domain powered by google) is shown valid not only on my tool but on all above famous online email verification tools. And of course these are invalid emails.

So @bighappyworld do you think it is related to SSL/TLS support issue..?

**Comment by bighappyworld** [comment]
If you are serious about finding the cause, you need to Telnet directly into the SMTP server, follow the back and forth SMTP protocol "conversation" manually, read the responses and figure it out from there.
