### ISSUE TITLE
Nemesis ESMTP Service not available - invalid DNS PTR resource record !!!

### ISSUE THREAD

**Issue by imrany** [bighappyworld/email-verify#41]
Hi, 

I am getting invalid address on a valid email address and error is 
"perfora.net (mxeueus003) Nemesis ESMTP Service not available
No SMTP service
invalid DNS PTR resource record, IP=182.185.147.xxx"

I have tested on multiple online email verifier 
https://hunter.io
https://tools.verifyemailaddress.io/

and they can successfully verified that email address.

Any idea how to fix this ?

Thanks,
Imran

**Comment by bighappyworld** [comment]
When you configure a email server, you need to configure a PTR record (Reverse DNS). If you are running this from an IP that is configured properly as an email server, it would have the PTR record. I could be completely wrong here, but maybe the mail server you are connecting to is validating that you are a real mail server with the PTR record. And when it finds that the IP doesn't match up, it rejects you.

Fixing this involves "tricking" the email server you are checking into thinking that you are a real SMTP mail server. PTR Records, DKIM, SPF etc. Likely the services that you name are doing exactly this which is why it works. They are running the query from an IP address that appears to be a mail server or even is a proper mail server.

**Comment by imrany** [comment]
OK, yes I am running this from my personal machine. And from the machine where I have to deploy is also not a email server. So could you please direct/guide me how to trick the remote email server that I am a real SMTP mail server ?

Thanks,
Imran
