### ISSUE TITLE
Whats the trick in NOT getting blacklisted?

### ISSUE THREAD

**Issue by thebarty** [bighappyworld/email-verify#42]
Hi guys,

I love the idea of the this package and am just trying it out. It works when testing it with my own mail-server (which does NOT have any spam protection), BUT it seems like on other domains I am getting a lot of false negatives due to blacklisting...

**Is there a trick to make this work better?** Maybe use a valid `options.sender` and `options.fqdn`?

Examples of "blacklisted" results I am getting:
```
// GMX
SERVER: 554-gmx.net (mxgmx016) Nemesis ESMTP Service not available
SERVER: 554-No SMTP service
SERVER: 554-IP address is black listed.
```

```
// RANDOM TARGET
SERVER: 451 4.3.0 Message temporarily deferred. Please try again later
```

**Comment by bighappyworld** [comment]
blacklisting could come from the ip address, especially if you are using some kind of shared ip address... this could be because your internet provider uses some kind of internal NAT (I've seen that where I am, called and asked for a non-NAT IP)... or if you are using a cloud service provider and running it there, it could be that someone used that same IP for spamming before.

to make it better, you'd want to make it look like the request is coming from a REAL mail server. this could be making sure the request is coming from the same IP as your real mail server... when they do a check at that IP for a reverse pointer record, it should be valid... make sure you have a valid SMTP server at that IP address in case there is a check for that. make sure that you have the SPF setup on the DNS and also the DKIM coming up valid if they check.

but, mostly the blacklisting ends up being out of your control because it's typically very simplistic and just an IP ban

**Comment by thebarty** [comment]
@bighappyworld: That sounds like you know what you are doing!

3 questions:
1) I am planning to scan run about 10 email scans per domain on up to 200 domains per day. Do you recon I'll be blacklisted pretty quick, even if I have the SPF and DKIM setup correctly?
2) Are there any npm-modules you can recon to setup an smtp "on the fly", including SPF and DKIM entries?
3) Do you know any npm package to send a real test-email and analyse bounces? I have spend some time searching, but have NOT found anything...

In the end the whole idea is to validate the emails BEFORE sending out to avoid a high bounce-rate from my real email....

**Comment by thebarty** [comment]
@bighappyworld any chance in getting some hints? :-)

**Comment by bighappyworld** [comment]
email is tricky, lots of different servers, different reasons to be blacklisted... different protocols, etc.

honestly if you want to try and "fake it" the easiest way is to run this on a mail server that you've already configured, Postfix / Dovecot or whatever suits you. if you are going to try and emulate the email server protocols and sort out DKIM / SPF, i don't have any idea how to help you there other than look into running a node SMTP server that works with those protocols and then configuring your DNS properly.
